### ISSUE TITLE
Not scaling down on examples/deployment_cronhpa_hpa.yml

### ISSUE THREAD

**Issue by ml497** [AliyunContainerService/kubernetes-cronhpa-controller#54]
This occurs on scale-down with the deployment_cronhpa_hpa.yml example:

`cron hpa job scale-down executed successfully. Skip scale replicas because HPA nginx-deployment-basic-hpa current replicas:3 >= desired replicas:1`

I'm a bit confused why it is doing this, it's not conflicting with the kubernetes HPA since both 3 and 1 are within range.  What is the reason that it won't scale down after scaling up?

**Comment by ringtail** [comment]
> This occurs on scale-down with the deployment_cronhpa_hpa.yml example:
> 
> `cron hpa job scale-down executed successfully. Skip scale replicas because HPA nginx-deployment-basic-hpa current replicas:3 >= desired replicas:1`
> 
> I'm a bit confused why it is doing this, it's not conflicting with the kubernetes HPA since both 3 and 1 are within range. What is the reason that it won't scale down after scaling up?

This is by design. If cronhpa scale down to the replica less than the current replica controlled by HPA. The replicas would be scaled up immediately. The purpose of cronhpa and hpa is to guarantee the stability of workload.  You can follow up the result of cronhpa. https://github.com/AliyunContainerService/kubernetes-cronhpa-controller/pull/45

**Comment by ml497** [comment]
Ok, thanks.  I understand now.  Scale-up and scale-down are modifying the 'Min replicas' field in the kubernetes HPA.
